update works!

diff --git a/code/coble b/code/coble
--- a/code/coble
+++ b/code/coble
@@ -42,13 +42,6 @@ if [[ "$1" == "capture" ]]; then
 	exit $?
 fi
 
-# If the first argument is 'recreate', call coble-recreate.sh and exit
-if [[ "$1" == "recreate" ]]; then
-	script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-	"$script_dir/coble-recreate.sh" "${@:2}"
-	exit $?
-fi
-
 # If the first argument is 'recipise', call coble-recipise.sh and exit
 if [[ "$1" == "recipise" || "$1" == "recipe" ]]; then
 	script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
@@ -63,8 +56,8 @@ if [[ "$1" == "resolve" || "$1" == "find" ]]; then
 	exit $?
 fi
 
-# If the first argument is 'create', call a succession of scripts checking status and exit
-if [[ "$1" == "build" ]]; then	
+# If the first argument is 'build or update', call a succession of scripts checking status and exit
+if [[ "$1" == "build" || "$1" == "update" ]]; then	
 	script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 	# TODO SKIP THIS IF sh passed in as input
 	echo "[coble-create 1/4] Resolving yml..." >&2
@@ -86,6 +79,18 @@ if [[ "$1" == "build" ]]; then
 		exit 0
 	fi	
 	
+	if [[ "$1" == "update" ]]; then	
+        echo "[coble-create 2.5/4] Created recipe, proceeding to make update portion." >&2
+		old_recipe="$recipe_file".old.sh
+		new_recipe="$recipe_file"
+		update_success=$("$script_dir/coble-update.sh" --old-recipe "$old_recipe" --new-recipe "$new_recipe")
+		if [[ $? -ne 0 ]]; then		 
+			echo "[coble-create] Error in updating recipe, please review logs before resuming." >&2
+			exit 0
+		fi
+		recipe_file="$new_recipe".update.sh		
+	fi
+
 	echo "[coble-create 3/4] Created recipe, proceeding to creation." >&2
 	result=$("$script_dir/coble-create.sh" --recipe "$recipe_file" "${@:2}")
 	if [[ $? -ne 0 ]]; then		 
