r works from template directly.

diff --git a/code/coble b/code/coble
--- a/code/coble
+++ b/code/coble
@@ -53,11 +53,17 @@ if [[ "$1" == "create" ]]; then
 	echo "[coble-create 2/4] Resolved yml, proceeding to rationalise." >&2
 	success=$("$script_dir/coble-rationalise.sh" "${@:2}")
 				
-	echo "[coble-create 2/4] Rationalised yml, proceeding to recipise." >&2
-	success=$("$script_dir/coble-recipise.sh" "${@:2}")
+	echo "[coble-create 2/4] Rationalised yml, proceeding to recipise." >&2	
+	mapfile -t result < <("$script_dir/coble-recipise.sh" "${@:2}")
+	success="${result[0]}"
+	recipe_file="${result[1]}"
+	if [[ "$success" == "N" ]]; then
+		echo "[coble-build] Error in creating recipe, please correct input before resuming." >&2
+		exit 0
+	fi	
 	
 	echo "[coble-create 3/4] Created recipe, proceeding to creation." >&2
-	#"$script_dir/coble-create.sh" "${@:2}"
+	result=$("$script_dir/coble-create.sh" --recipe "$recipe_file" "${@:2}")
 	
 	echo "[coble-create 4/4] Created env, proceeding to capture." >&2
 	#"$script_dir/coble-capture.sh" "${@:2}"
