docs update

diff --git a/code/coble b/code/coble
--- a/code/coble
+++ b/code/coble
@@ -42,22 +42,22 @@ fi
 if [[ "$1" == "build" || "$1" == "update" ]]; then	
 	script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 	# TODO SKIP THIS IF sh passed in as input
-	echo "[coble-create 1/5] Resolving yml..." >&2
+	echo "[*coble 1/5] Resolving yml..." >&2
 	finds=$("$script_dir/coble-resolve.sh" "${@:2}")
 	if [[ "$finds" == "Y" ]]; then
-		echo "[coble-create] Finds were resolved, please check the yml input before resuming." >&2
+		echo "[*coble] Finds were resolved, please check the yml input before resuming." >&2
 		exit 0
 	fi	
 	
-	echo "[coble-create 2/5] Resolved yml, proceeding to rationalise." >&2
+	echo "[*coble 2/5] Resolved yml, proceeding to rationalise." >&2
 	success=$("$script_dir/coble-rationalise.sh" "${@:2}")
 				
-	echo "[coble-create 2/5] Rationalised yml, proceeding to recipise." >&2	
+	echo "[*coble 3/5] Rationalised yml, proceeding to recipise." >&2	
 	mapfile -t result < <("$script_dir/coble-recipise.sh" "${@:2}")
 	success="${result[0]}"
 	recipe_file="${result[1]}"
 	if [[ "$success" == "N" ]]; then
-		echo "[coble-build] Error in creating recipe, please correct input before resuming." >&2
+		echo "[*coble] Error in creating recipe, please correct input before resuming." >&2
 		exit 0
 	fi	
 	
@@ -66,20 +66,20 @@ if [[ "$1" == "build" || "$1" == "update" ]]; then
 	capture_file="$recipe_file.capture.yml"
 	
 	if [[ "$1" == "build" ]]; then
-	    echo "[coble-create 3/5] Created recipe, rebuilding environment." >&2
+	    echo "[*coble 3/5] Created recipe, rebuilding environment." >&2
 	    : > "$done_recipe"
 		: > "$summary_file"
 	elif [[ "$1" == "update" ]]; then	
 	    if [[ ! -f "$done_recipe" ]]; then
 			: > "$done_recipe"
 			: > "$summary_file"			
-			echo "[coble-create 3/5] Created recipe, building environment." >&2
+			echo "[*coble 3/5] Created recipe, building environment." >&2
 		else
 		    
-			echo "[coble-create 3/5] Created recipe, updating environment." >&2
+			echo "[*coble 3/5] Created recipe, updating environment." >&2
 		fi
 	else
-		echo "[coble-create] Unknown command: $1" >&2
+		echo "[*coble] Unknown command: $1" >&2
 		exit 1
 	fi
 		
@@ -88,37 +88,37 @@ if [[ "$1" == "build" || "$1" == "update" ]]; then
 
 	update_success=$("$script_dir/coble-update.sh" --done-recipe "$done_recipe" --all-recipe "$recipe_file")
 	if [[ $? -ne 0 ]]; then		 
-		echo "[coble-create] Error in updating recipe, please review logs before resuming." >&2
+		echo "[*coble] Error in updating recipe, please review logs before resuming." >&2
 		exit 0
 	fi		
-	echo "[coble-create 4/5] Created recipe, proceeding to creation." >&2
+	echo "[*coble 4/5] Created recipe, proceeding to creation." >&2
 	recipe_file="$recipe_file".delta.sh
 	result=$("$script_dir/coble-create.sh" --recipe "$recipe_file" "${@:2}")
 	if [[ $? -ne 0 ]]; then		 
-		echo "[coble-create] Error in environment creation, please review logs before resuming." >&2
+		echo "[*coble] Error in environment creation, please review logs before resuming." >&2
 
 		end_time=$(date +%s)
 	    duration=$((end_time - start_time))
 	    hours=$((duration / 3600))
 	    minutes=$(((duration % 3600) / 60))
 	    seconds=$((duration % 60))
-	    echo "[coble-create] Time taken to get here $(date) (Duration: ${hours}h ${minutes}m ${seconds}s)" >&2	
+	    echo "[*coble] Time taken to get here $(date) (Duration: ${hours}h ${minutes}m ${seconds}s)" >&2	
 		exit 0
 	fi
 	
-	echo "[coble-create 5/5] Created env, proceeding to capture." >&2	
+	echo "[*coble 5/5] Created env, proceeding to capture." >&2	
 	recipe_dir="$(dirname "$recipe_file")"	
 	result=$("$script_dir/coble-capture.sh" --outdir "$recipe_dir" --output "$capture_file" "${@:2}")
 		
-	echo "[coble-create] Environment creation complete." >&2
+	echo "[*coble] Environment creation complete." >&2
 	end_time=$(date +%s)
 	duration=$((end_time - start_time))
 	hours=$((duration / 3600))
 	minutes=$(((duration % 3600) / 60))
 	seconds=$((duration % 60))
-	echo "[coble] Completed coble at $(date) (Duration: ${hours}h ${minutes}m ${seconds}s)" >&2	
+	echo "[*coble] Completed coble at $(date) (Duration: ${hours}h ${minutes}m ${seconds}s)" >&2	
 	exit $?
 fi
 
-echo "Not a valid command provided: $1."
+echo "[*coble] Not a valid command provided: $1." >&2
 show_help
